gcc -Wall -Wextra -Werror -D BUFFER_SIZE=32 get_next_line.c get_next_line_utils.c

JUSTE RAPPEL DE LA LIGNE DE COMMANDE, PAS DE MAKEFILE
edgesd
fhxggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg!


