gcc -Wall -Wextra -Werror -D BUFFER_SIZE=32 get_next_line.c get_next_line_utils.c
gcc -Wall -Wextra -Werror -D BUFFER_SIZE=32 get_next_line_bonus.c get_next_line_utils_bonus.c

JUSTE RAPPEL DE LA LIGNE DE COMMANDE, PAS DE MAKEFILE
edgesd
fhxggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg!
1
2
LAST LINE